#base image : alpine is used for its small size
FROM alpine

# package or dependencies
RUN apk add --update redis

#command to run images
CMD [ "echo","Hello Ali ,I Am Your Custom Image, REDIS-SERVER" ]
