apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: efg-hermes-ingress
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: efg-hermes-api
            port: 
              number: 8080
      - path: /frontend
        pathType: Prefix
        backend:
          service:
            name: efg-hermes-frontend
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: efg-hermes-frontend
            port:
              number: 3000